## Tipos de Datos

In [7]:
#String
# cree una variable llamada mi_string 
mi_string = "cualquier cosa"

In [3]:
type(mi_string)

str

In [4]:
len(mi_string)

14

In [5]:
range(len(mi_string))

range(0, 14)

In [48]:
filename = "/my_path/hola.fasta"

In [49]:
str(filename)

'/my_path/hola.fasta'

In [62]:
uno = "123"

In [63]:
dos = "234"

In [65]:
uno + dos

'123234'

In [66]:
uno = 1
dos = 2

uno / dos

0.5

Lista

In [18]:
# Listas
lista_1 = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]

In [19]:
lista_2 = [0, "hola", {"hola":2}, [1,2,3,4]]

In [24]:
diccionario = {"10000":{"user_name": "Emilio",
 "emial": "email@gmail.com"},
               "10001":{"user_name": "Juan",
 "emial": "email@gmail.com"},
               "10002":{"user_name": "x",
 "emial": "email@gmail.com"},
               "10003":{"user_name": "y",
 "emial": "email@gmail.com"}}

Suma de lista

In [67]:
lista = [1,2,3]
lista_2 = ["hola",3,4]

lista + lista_2

[1, 2, 3, 'hola', 3, 4]

In [73]:
lista_3 = [lista + lista_2]

In [77]:
lista_3[0][1]

2

Diccionario

In [28]:
diccionario = { 
    "exp_0": {"resultado": [1,3,4,5], "fecha": "10-02-2024"},
    "exp_1": {"resultado": [1,5,4,1], "fecha": "10-02-2024"}   
}

In [36]:
exp_0 = diccionario["exp_0"]
print(f"todo el objeto: {exp_0}")

exp_0_resutlados = exp_0["resultado"]
print(f"solo el resultado: {exp_0_resutlados}")

promedio = sum(exp_0_resutlados)/len(exp_0_resutlados)
print(f"promedio: {promedio}")

print("########")

exp_1 = diccionario["exp_1"]
print(f"todo el objeto: {exp_1}")

exp_1_resutlados = exp_1["resultado"]
print(f"solo el resultado: {exp_1_resutlados}")

promedio = sum(exp_1_resutlados)/len(exp_1_resutlados)
print(f"promedio: {promedio}")

todo el objeto: {'resultado': [1, 3, 4, 5], 'fecha': '10-02-2024'}
solo el resultado: [1, 3, 4, 5]
promedio: 3.25
########
todo el objeto: {'resultado': [1, 5, 4, 1], 'fecha': '10-02-2024'}
solo el resultado: [1, 5, 4, 1]
promedio: 2.75


In [33]:
for exp, resumen in diccionario.items():
    print(exp, resumen)
    print(sum(resumen["resultado"])/len(resumen["resultado"]))

exp_0 {'resultado': [1, 3, 4, 5], 'fecha': '10-02-2024'}
3.25
exp_1 {'resultado': [1, 5, 4, 1], 'fecha': '10-02-2024'}
2.75


In [9]:
for contador in range(len(mi_string)):
    print(mi_string[contador])
    

c
u
a
l
q
u
i
e
r
 
c
o
s
a


In [44]:
# Dictionary
parser = [{"ID": "Genoma_CpI19_Refinada_v2",
          "Description": "",
          "Sequence": "GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTGAGCTACTGCAC"},
          {"ID": "Genoma_de_mentira",
          "Description": "blablabla",
          "Sequence": "GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTG"}]

In [46]:
parser[1]

{'ID': 'Genoma_de_mentira',
 'Description': 'blablabla',
 'Sequence': 'GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTG'}

In [47]:
for seq in parser:
    print('ID:', seq['ID'])
    print('Description:', seq['Description'])
    print('Sequence:', seq['Sequence'])
    print()

ID: Genoma_CpI19_Refinada_v2
Description: 
Sequence: GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTGAGCTACTGCAC

ID: Genoma_de_mentira
Description: blablabla
Sequence: GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGA

## Algebra lineal

In [79]:
import numpy as np

In [81]:
x = np.array([1,2,3,4])

In [82]:
y = np.array([3,4,5,6])

In [83]:
x

array([1, 2, 3, 4])

In [84]:
y

array([3, 4, 5, 6])

In [85]:
x+y

array([ 4,  6,  8, 10])

In [86]:
np.dot(x,y)

50

## Ejercicio: corroborar que una secuencia está corrupta

In [99]:
secuencia = parser[0]["Sequence"]

In [100]:
secuencia

'GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTGAGCTACTGCAC'

In [90]:
type(secuencia)

str

In [91]:
set(secuencia)

{'A', 'C', 'G', 'T'}

In [106]:
# metodo o funcion
def advertencia(secuencia: str)-> None:
    """
    Este método recibe una secuencia de ADN en formato str
    y devuelve un error en caso de que esté corrupta la secuencia.
    Args:
        secuencia (str): secuencia de ADN en formato string. Por ejemplo: 'TCCATCGACATGGAACGAGCGGTGGCAAGAAG'
    Return: 
        None
    """

    # Conocimiento 
    ref = {'A', 'C', 'G', 'T'}

    if ref == set(secuencia):
        print("Secuencia sin problemas!") 
    else:
        print(f"ERROR, el elemento diferente es: {set(secuencia).difference(ref)}")  

In [107]:
advertencia(secuencia)

Secuencia sin problemas!


Secuencia corrupta

In [108]:
secuencia_corrupta = parser[0]["Sequence"]+'W'

In [109]:
secuencia_corrupta

'GTGTCGGAGGCTCCATCGACATGGAACGAGCGGTGGCAAGAAGTTACTAATGAGCTGCTGTCACAGTCTCAGGACCCGGAAAGTGGTATTTCCATTACGCGACAGCAAAGCGCCTACCTGCGTCTGGTTAAACCAGTTGCTTTTGTAGAGGGTATTGCCGTTTTAAGCGTTCCTCACGCCCGAGCGAAAAAAGAGATTGAAACTACGCTGGGACCTGTTATCACAGAGGTATTGTCTCGTAGACTAGGTCGACAATACAGTCTTGCAGTGAGCGTTCATGCTCCAGAGGAAAATCCAGAAGTATCCTCGGCCACTCCAGATGCTGTGTCTTATTACCAGGAACAATCTGCAGTTTCTGGACAATACGGAGCAACTTCAGCCAATGCTGACTTCCAGAATCAACAAAGCACGATATATCGCAAGCCACAGGAGTCGCAGTATCCTGTGACTTTTGGTGCTTCTTCATACGGAAATGAGAAGTACCAGGAAAATTCCCAAGACCAGGGCATTTCTCATCATCCTTATGGTTTTAATGAGGCTCAACGCATTGCTTCATCTGCCTCTCATGCTGTTCCGCAAAGTGGTTCTGAGCTACTGCACW'

In [110]:
advertencia(secuencia_corrupta)

ERROR, el elemento diferente es: {'W'}
